### ISSUE TITLE
Implement ORAS artifacts-spec RC1

### ISSUE THREAD

**Issue by aviral26** [oras-project/distribution#4]
This issue tracks the status of an implementation of RC1 specification of https://github.com/oras-project/artifacts-spec https://github.com/oras-project/artifacts-spec/releases/tag/v1.0.0-rc.1

- [ ] Enable extension configuration framework
- [x] PUT ORAS Artifact Manifest
- [x] GET ORAS Artifact Manifest
- [x] LIST referrers
- [x] Sort by `io.cncf.oras.artifact.created`
- [x] Filtering by artifact type 
- [ ] Pagination support for referrers
- [x] Rebase from distribution/distribution `v2.8.1` and cut branch `rc1` by cherry-picking from `ext_oras`
- [ ]  Create a Tag for branch and also for distribution so that users can pull `ghcr.io/oras-project/registry:v2.8.1-oras-rc1`

## Post release items 
Garbage collection is currently marked out of scope for RC1 but would be needed before we submit the changes to distribution/distribution 

-  [ ] Documentation of storage changes needed to support referrers 
-  [ ] GC implementation with tests for invoking GC of referrers.

**Comment by akashsinghal** [comment]
Starting to work on rc1 implementation

**Comment by akashsinghal** [comment]
Current status:
1. All RC1 support tasks completed: PUT, GET, LIST referrers; Extension framework enabled; Sorting, filtering, pagination
2. Rebased off latest distribution:main branch
3. Created v1.0.0-rc1 tag and release published

In Progress:
1. Garbage Collection
2. Extension framework updates

Todo:
1. Cherrypick changes for extension framework to propose upstream
2. Float design document with extension implementation proposal

**Comment by akashsinghal** [comment]
Completed RC1 and RC2 release. I think we should close this now @aviral26
