### ISSUE TITLE
Add @avtakkar as release manager for oras-project/distribution

### ISSUE THREAD

**Issue by sajayantony** [oras-project/distribution#6]
I would like to recommend adding @avtakkar as the release manager for ORAS. This would follow the process and guidelines described in PR https://github.com/oras-project/community/pull/8. 

Currently this is tracked only through issues and would like to get recommendation on if we should keep track of sub-project owners. But given that this is a fork, I'm leaning on just tracking it through an issue. 

/cc @lachie83 @SteveLasker @jdolitsky @deitch

**Comment by SteveLasker** [comment]
LGTM

**Comment by deitch** [comment]
Ditto. LGTM

**Comment by sajayantony** [comment]
Thanks you I’m adding @avtakkar as per . oras-project/community#8
